<?php

declare(strict_types=1);

namespace Stringer\Laravel\Enums;

/**
 * Provenance of a BlogTopic — how it entered the queue.
 *
 * `Manual` — typed into Telegram or the Filament admin.
 * `Repo` / `Project` — synthesized from a polymorphic host record.
 * `Auto` — generated by the weekly auto-draft job.
 */
enum TopicSource: string
{
    case Manual = 'manual';
    case Repo = 'repo';
    case Project = 'project';
    case Auto = 'auto';
}
